name: Main

on:
  workflow_dispatch:
  push:
    branches:
      main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
          source-url: https://nuget.pkg.github.com/toletus/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Set version number environment variable
        env:
          github_ref: ${{ github.ref }}
        run: |
          version='7.${{ github.run_number }}.${{ github.run_attempt }}'
           echo version=$version
           echo "version=$version" >> $GITHUB_ENV

      - name: Build with dotnet
        run: |
          dotnet build "src/Toletus.LiteNet2.Base/Toletus.LiteNet2.Base.csproj" --configuration Release -p:Version=${{ env.version }}

      - name: Create the Package
        run: |
          dotnet pack "src/Toletus.LiteNet2.Base/Toletus.LiteNet2.Base.csproj" --configuration Release /p:PackageVersion=${{ env.version }}  #-beta

      - name: Publish Toletus.LiteNet2.Base
        run: dotnet nuget push "src/Toletus.LiteNet2.Base/bin/Release/*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/toletus/index.json --skip-duplicate
